#!/usr/bin/env bash
# docs-sync.sh — mirror a feature directory into the Starlight docs site.
#
# The canonical source for specs/plans/tasks is repo-root `specs/NNN-<slug>/`. The
# docs site (docs/, Astro + Starlight) renders a single autogenerated "Features"
# section from `docs/src/content/docs/features/`. This script copies a feature
# directory there so the site picks it up, injecting the `title:` frontmatter that
# Starlight's docsSchema requires (derived from each file's first `# ` heading, or
# the filename). It copies/overwrites only — it never deletes (no `rm`), so removing
# a feature from the site is a manual step.
#
# Usage:
#   docs-sync.sh specs/NNN-<slug>
#
# Exit codes: 0 ok; 2 bad usage; 1 source missing.
set -euo pipefail

src="${1:-}"
if [[ -z "$src" ]]; then
  echo "usage: docs-sync.sh <feature-dir, e.g. specs/001-foo>" >&2
  exit 2
fi
src="${src%/}"
if [[ ! -d "$src" ]]; then
  echo "error: no such feature directory: $src" >&2
  exit 1
fi

feature="$(basename "$src")"
dest="docs/src/content/docs/features/$feature"
mkdir -p "$dest"

# Copy every markdown file, prepending Starlight frontmatter when absent.
while IFS= read -r f; do
  rel="${f#"$src"/}"
  out="$dest/$rel"
  mkdir -p "$(dirname "$out")"
  if head -n1 "$f" | grep -q '^---[[:space:]]*$'; then
    # already has frontmatter — copy verbatim
    cp "$f" "$out"
  else
    # derive a title from the first markdown H1, else from the relative path
    title="$(grep -m1 '^# ' "$f" 2>/dev/null | sed 's/^#[[:space:]]*//' | sed 's/"/\\"/g')"
    [[ -z "$title" ]] && title="${feature} — ${rel}"
    {
      printf -- '---\n'
      printf 'title: "%s"\n' "$title"
      printf -- '---\n\n'
      cat "$f"
    } > "$out"
  fi
done < <(find "$src" -type f \( -name '*.md' -o -name '*.mdx' \) 2>/dev/null)

# Copy any non-markdown artifacts (e.g. contracts/*.json) verbatim.
while IFS= read -r f; do
  rel="${f#"$src"/}"
  out="$dest/$rel"
  mkdir -p "$(dirname "$out")"
  cp "$f" "$out"
done < <(find "$src" -type f ! -name '*.md' ! -name '*.mdx' 2>/dev/null)

echo "synced $src -> $dest"
